# Generated by Django 3.2.15 on 2022-11-14 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255)),
                ('cts_number', models.CharField(max_length=255)),
                ('room_number', models.CharField(max_length=255)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_permanent_address', models.CharField(max_length=1024)),
                ('tenant_mobile_number', models.IntegerField(blank=True, null=True)),
                ('tenant_dod', models.DateField(blank=True, null=True)),
                ('tenant_gender', models.CharField(max_length=255)),
                ('bill_for_month_of', models.CharField(max_length=20)),
                ('book_number', models.IntegerField(blank=True, null=True)),
                ('bill_number', models.IntegerField(blank=True, null=True)),
                ('purpose_for', models.CharField(max_length=510)),
                ('rent_from', models.CharField(max_length=20)),
                ('rent_to', models.CharField(max_length=20)),
                ('at_the_rate_of', models.IntegerField(blank=True, null=True)),
                ('total_months', models.IntegerField(blank=True, null=True)),
                ('total_rupees', models.IntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('extra_payment', models.IntegerField(blank=True, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=1020)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CTSNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cts_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HouseNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255)),
                ('cts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr_app.ctsnumber')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr_app.housenumber')),
            ],
        ),
        migrations.CreateModel(
            name='TenantAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_permanent_address', models.CharField(max_length=1024)),
                ('tenant_mobile_number', models.IntegerField(blank=True, null=True)),
                ('tenant_dod', models.DateField(blank=True, null=True)),
                ('tenant_gender', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rr_app.roomnumber')),
            ],
        ),
        migrations.AddField(
            model_name='ctsnumber',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rr_app.housenumber'),
        ),
    ]
