# Generated by Django 3.2.15 on 2022-11-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tenantattributes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
