# Generated by Django 3.2.15 on 2023-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0002_auto_20221119_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenantattributes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
