# Generated by Django 3.2.6 on 2022-05-21 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0003_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
