# Generated by Django 3.2.6 on 2022-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rr_app', '0004_delete_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=255)),
                ('tenant_name', models.CharField(max_length=255)),
                ('tenant_permanent_address', models.CharField(max_length=1024)),
                ('tenant_mobile_number', models.IntegerField(blank=True, null=True)),
                ('tenant_dod', models.DateField(blank=True, null=True)),
                ('tenant_gender', models.CharField(max_length=255)),
                ('bill_for_month_of', models.CharField(max_length=20)),
                ('book_number', models.IntegerField(blank=True, null=True)),
                ('bill_number', models.IntegerField(blank=True, null=True)),
                ('purpose_for', models.CharField(max_length=510)),
                ('rent_from', models.CharField(max_length=20)),
                ('rent_to', models.CharField(max_length=20)),
                ('at_the_rate_of', models.IntegerField(blank=True, null=True)),
                ('total_months', models.IntegerField(blank=True, null=True)),
                ('total_rupees', models.IntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('extra_payment', models.IntegerField(blank=True, null=True)),
                ('agreement_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(max_length=1020)),
            ],
        ),
    ]
